---
name: "Dual Samba Server"
description: "Dual Samba server for legacy Canon scanner and modern Windows access"
url: "https://github.com/hunhejj/hassio-addons"
version: "1.0.0"
slug: samba_dual
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
startup: application
boot: auto
map:
  - share:rw
ports:
  139/tcp: 139
  445/tcp: 445
ports_description:
  139/tcp: "NetBIOS Session Service"
  445/tcp: "SMB over TCP"
options:
  workgroup: "WORKGROUP"
  legacy_ip: "192.168.0.254"
  username: "scanner"
  password: "CHANGEME!"
schema:
  workgroup: str
  legacy_ip: str
  username: str
  password: str
