name: "Dual Samba Server"
version: "1.0.0"
slug: samba_dual
description: "Dual Samba server for legacy Canon scanner and modern Windows access"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_network: true
ports:
  139/tcp: 139
  445/tcp: 445
ports_description:
  139/tcp: "NetBIOS Session Service"
  445/tcp: "SMB over TCP"
options:
  workgroup: "WORKGROUP"
  legacy_ip: "192.168.0.254"
  username: "scanner"
  password: "CHANGEME!"
schema:
  workgroup: str
  legacy_ip: str
  username: str
  password: str
map:
  - share:rw
startup: services
boot: auto
